openapi: 3.0.0
info:
  title: Recipe API
  version: 1.0.0
paths:
  /api/recipes:
    get:
      summary: Get all recipes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Recipe'
  /api/recipes/{recipeId}:
    parameters:
      - in: path
        name: recipeId
        schema:
          type: integer
        required: true
    get:
      summary: Get a recipe by ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
  /api/recipes/{recipeId}/ingredients:
    parameters:
      - in: path
        name: recipeId
        schema:
          type: integer
        required: true
    get:
      summary: Get a recipe ingredients by recipeId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecipeIngredient'
  /api/recipes/{recipeId}/steps:
    parameters:
      - in: path
        name: recipeId
        schema:
          type: integer
        required: true
    get:
      summary: Get a recipe steps by recipeId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecipeStep'
  /api/users:
    get:
      summary: Get all users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /api/users/{userId}:
    parameters:
      - in: path
        name: userId
        schema:
          type: integer
        required: true
    get:
      summary: Get a user by ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    Recipe:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        userId:
          type: integer
      required:
        - id
        - title
        - description
        - userId
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
        - id
        - name
    RecipeIngredient:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        amount:
          type: string
        recipeId:
          type: integer
      required:
        - id
        - name
        - amount
        - recipeId
    RecipeStep:
      type: object
      properties:
        id:
          type: integer
        order:
          type: integer
        description:
          type: string
        recipeId:
          type: integer
      required:
        - id
        - order
        - description
        - recipeId
    RecipeStepImage:
      type: object
      properties:
        id:
          type: integer
        imageUrl:
          type: string
        recipeStepId:
          type: integer
      required:
        - id
        - imageUrl
        - recipeStepId
